#!/bin/bash
# init_tmp.sh - Initialize all .tmp log stubs for agent workflows
# Generated by Antigravity Coordinator — 2026-03-01
# Run from project root: bash execution/init_tmp.sh

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TMP_DIR="$PROJECT_ROOT/.tmp"

mkdir -p "$TMP_DIR"

LOGS=(
  # check-logs.md: Backend
  "backend.log"
  "backend_deploy.log"
  "backend_test.log"
  "backend_verification.log"
  "weather_test.log"
  # check-logs.md: Frontend
  "frontend.log"
  "frontend_build.log"
  # check-logs.md: QA
  "qa.log"
  "serialization_test.log"
  "manual_api_test.log"
  # check-logs.md: Security
  "security.log"
  # QA directive / phase0
  "phase0.log"
  # Coordinator bootstrap
  "npm_install.log"
  "npm_audit.log"
  "dfx_start.log"
  "dfx_deploy.log"
)

TS=$(date -u '+%Y-%m-%dT%H:%M:%SZ')

for f in "${LOGS[@]}"; do
  FILE="$TMP_DIR/$f"
  if [ ! -f "$FILE" ] || [ ! -s "$FILE" ]; then
    echo "[$TS] Log initialized — awaiting first run. (init_tmp.sh)" > "$FILE"
    echo "  created: $f"
  else
    echo "  skipped (exists): $f"
  fi
done

echo ""
echo "=== .tmp contents ==="
ls -lh "$TMP_DIR"
echo ""
echo "✅ .tmp initialized at: $TMP_DIR"
