// @vitest-environment node
//
// QUAL-06 — Candid contract guard.
//
// This is the cheapest gate in the whole test pyramid and it targets a failure
// mode this repo has already suffered: the backend renames or drops a method,
// nothing at build time notices, and the caller only breaks at runtime. It is
// exactly what rotted the shell suite — `test_rankings.sh` still calls
// `getLeaderboard` (now `getGlobalLeaderboard`) and `e2e_backend.sh` still
// calls `advanceSeason` (removed entirely). Both scripts sat "green-looking"
// and broken in the repo for months.
//
// HOW: the method list is not hand-maintained. It is read at runtime out of the
// generated `idlFactory` — i.e. out of the actual Candid interface — and
// compared against the `backendActor.<method>(...)` call sites found by
// scanning the frontend source. So the test fails if either side moves.
//
// Node environment (not jsdom) because it reads the source tree from disk.

import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { IDL } from '@dfinity/candid';
import { idlFactory } from '@/declarations/backend.did.js';

const SRC_ROOT = new URL('..', import.meta.url).pathname; // frontend/src

// ── the authoritative side: whatever the generated Candid actually declares ──

interface IdlMethod {
    name: string;
    isQuery: boolean;
}

function idlMethods(): IdlMethod[] {
    // idlFactory is generated by `dfx generate`; evaluating it yields an
    // IDL.Service whose _fields are [methodName, IDL.Func] pairs.
    const service = idlFactory({ IDL }) as unknown as {
        _fields: Array<[string, { annotations?: string[] }]>;
    };
    return service._fields.map(([name, func]) => ({
        name,
        isQuery: (func.annotations ?? []).includes('query'),
    }));
}

// ── the consumer side: what the frontend actually calls ─────────────────────

// Directories that are not application code and must stay out of the scan:
//  - declarations: the generated contract itself, not a consumer of it
//  - __tests__:    includes THIS file, whose error-message template literal
//                  contains a `backendActor.foo()` example that the scanner
//                  would otherwise pick up as a real call site
//  - test-utils:   fixtures and harness helpers
const SKIP_DIRS = new Set(['declarations', '__tests__', 'test-utils']);

function walk(dir: string, out: string[] = []): string[] {
    for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        if (statSync(full).isDirectory()) {
            if (SKIP_DIRS.has(entry)) continue;
            walk(full, out);
        } else if (/\.(ts|tsx)$/.test(entry)) {
            out.push(full);
        }
    }
    return out;
}

interface CallSite {
    method: string;
    file: string;
}

/**
 * Finds `backendActor.foo(`, `backendActor!.foo(` and `backendActor?.foo(`
 * usages. Deliberately a source scan rather than a curated list: a curated
 * list is one more thing that can drift, which is the bug being guarded.
 */
function frontendCallSites(): CallSite[] {
    const pattern = /backendActor[!?]?\.\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\(/g;
    const sites: CallSite[] = [];
    for (const file of walk(SRC_ROOT)) {
        const text = readFileSync(file, 'utf8');
        for (const match of text.matchAll(pattern)) {
            sites.push({ method: match[1], file: relative(SRC_ROOT, file) });
        }
    }
    return sites;
}

// ── assertions ──────────────────────────────────────────────────────────────

describe('Candid contract: every backend method the frontend calls exists', () => {
    const declared = idlMethods();
    const declaredNames = new Set(declared.map((m) => m.name));
    const sites = frontendCallSites();

    it('finds call sites to check (guards against the scanner silently breaking)', () => {
        // If a refactor renames the actor variable, the regex would match
        // nothing and this suite would pass while checking absolutely nothing.
        expect(sites.length).toBeGreaterThan(20);
        expect(declared.length).toBeGreaterThan(20);
    });

    it.each(
        [...new Set(sites.map((s) => s.method))].sort().map((m) => [m] as const)
    )('%s is declared in the Candid interface', (method) => {
        const callers = sites.filter((s) => s.method === method).map((s) => s.file);
        expect(
            declaredNames.has(method),
            `The frontend calls backendActor.${method}() in [${[...new Set(callers)].join(', ')}] ` +
            `but the generated Candid interface declares no such method. Either the backend ` +
            `renamed/removed it (fix the caller) or the declarations are stale ` +
            `(run \`dfx generate backend\`).`
        ).toBe(true);
    });
});

describe('Candid contract: methods removed from the backend are no longer called', () => {
    // Named explicitly because these two are the historical evidence for why
    // this guard exists — both are still referenced by execution/tests/*.sh.
    const REMOVED_METHODS = ['getLeaderboard', 'advanceSeason'];

    it.each(REMOVED_METHODS)('%s is absent from the Candid interface', (method) => {
        const declaredNames = new Set(idlMethods().map((m) => m.name));
        expect(
            declaredNames.has(method),
            `"${method}" reappeared in the Candid interface. If the backend genuinely ` +
            `re-added it, drop it from REMOVED_METHODS here and re-check the legacy ` +
            `shell scripts that still call it.`
        ).toBe(false);
    });

    it.each(REMOVED_METHODS)('the frontend does not call %s', (method) => {
        const called = new Set(frontendCallSites().map((s) => s.method));
        expect(called.has(method)).toBe(false);
    });
});

describe('Candid contract: surface inventory', () => {
    it('reports declared methods the frontend never calls (informational)', () => {
        const declared = idlMethods();
        const called = new Set(frontendCallSites().map((s) => s.method));
        const unused = declared
            .map((m) => m.name)
            .filter((n) => !called.has(n) && !n.startsWith('_'))
            .sort();

        // NOT a failure: the canister legitimately exposes debug/admin surface
        // and not-yet-wired features. Printed so the unused surface stays
        // visible — several of these are known dead ends (e.g. buyInsurance,
        // purchaseCropInsurance) tracked as separate roadmap items.
        console.log(`[candid] ${unused.length} declared method(s) not called from the frontend:\n  ${unused.join('\n  ')}`);
        expect(Array.isArray(unused)).toBe(true);
    });

    it('exposes the query/update split the frontend relies on', () => {
        const declared = idlMethods();
        const queries = declared.filter((m) => m.isQuery).map((m) => m.name);

        // These are read paths that must stay cheap `query` calls — promoting
        // any of them to an update call would silently add consensus latency
        // to every render that uses them.
        for (const readPath of [
            'getPlayerFarm',
            'getFarmOverview',
            'getGlobalLeaderboard',
            'getMarketPrices',
            'getPlayerRank',
            'checkStability',
        ]) {
            expect(queries, `${readPath} should be a query method`).toContain(readPath);
        }
    });
});
