export const gddCompetitionSection = {
  id: 'competition-mechanics',
  title: 'Competition & Market Dynamics',
  content: `
## Shared Market Mechanics
The cherry market in Mark Vinicius Cherry Tycoon is not static; it is a living economy driven by supply and demand. The market price for cherries is influenced by the total supply generated by both the player and AI competitors.
- **Supply & Demand**: High total production across the region floods the market, driving retail and wholesale prices down. Conversely, a poor harvest season (due to weather or pests) creates scarcity, pushing prices up.
- **Market Saturation**: If the market becomes saturated with a specific cherry variety, its premium drops. Players must observe market trends and competitor planting strategies to avoid oversupplied niches.

## AI Competitor Behavior Patterns
Three distinct AI personalities compete against you, each with unique strategies that affect market dynamics:

### 1. The Traditionalist
- **Personality**: Risk-averse, relies on time-tested farming methods.
- **Strategy**: Plants standard, reliable cherry varieties. Rarely invests in expensive technology or risky organic conversions.
- **Market Impact**: Provides a steady, predictable supply of base-quality cherries. Stabilizes the lower-end market price.
- **Reaction**: Slow to react to price spikes; rarely changes crops.

### 2. The Innovator
- **Personality**: Tech-savvy, loves experimentation and high risk/high reward.
- **Strategy**: Early adopter of new irrigation systems and fertilizers. Focuses on premium, difficult-to-grow varieties and organic farming.
- **Market Impact**: Supply is volatile—can produce high-quality bumper crops or suffer massive failures. Drives prices for premium cherries.
- **Reaction**: Chases trends aggressively. If organic prices spike, they convert immediately.

### 3. The Businessman
- **Personality**: Profit-driven calculator, focuses on scaling and efficiency.
- **Strategy**: Aggressive expansion. Buys land rapidly and focuses on high-yield, disease-resistant varieties to maximize volume over quality.
- **Market Impact**: floods the market with volume, putting significant downward pressure on wholesale prices.
- **Reaction**: Highly reactive to profit margins. Will undercut competitors in auctions to secure contracts.

## Ranking System
Players are ranked regionally against AI competitors based on three key metrics:
1.  **Farm Value**: The total liquidated value of all assets.
    -   *Calculation*: (Land Value + Infrastructure Value + Machinery + Current Cash).
2.  **Season Profit**: The net income generated in the current season.
    -   *Calculation*: (Total Revenue from Sales/Contracts - Operating Outcomes - Wages).
3.  **Efficiency**: A measure of farming mastery.
    -   *Calculation*: (Total Yield (kg) / Total Arable Land (ha)) * (Average Quality Score).

## Auction-based Wholesale Contracts
Wholesale contracts offer guaranteed sales but are secured through a competitive auction system.
-   **Auction Timing**: Auctions occur at the beginning of each season.
-   **Bidding**: It is a blind bid system. You submit your best offer (price per kg and guaranteed quantity) to potential buyers (supermarkets, jamming factories).
-   **Winning**: The buyer selects the bid that offers the best value (lowest price for the required quality/quantity).
-   **Contracts**: Winning a bid secures a contract for the season. You definitively sell that quantity at the bid price.
-   **Penalties**: Failure to deliver the promised quantity results in a heavy fine and a reputation hit, reducing future auction chances.

## Cherry Festival Mechanics
The **Cherry Festival** is the grand culmination of the harvest year.
-   **Timing**: Held annually in late Summer, after the main harvest.
-   **Objectives**: Farmers submit their best cherry batch for judging based on Size, Sweetness, and Color.
-   **Scoring**: Judges (AI) score entries on a 1-10 scale.
-   **Rewards**:
    -   *1st Place*: "Golden Cherry" Trophy, +20% Market Price premium for the following year (brand reputation), and a cash prize.
    -   *Top 3*: Reputation boost, unlocking special vendor offers.
-   **Market Interaction**: Winning the festival increases demand for your specific brand, temporarily decoupling your retail prices from the general market trend.
`
};
